### ISSUE TITLE
jar name

### ISSUE THREAD

**Issue by durmuse** [rholder/gradle-one-jar#14]
I was wondering if we can give a name to the jar file instead of the name it produces by default?

**Comment by rholder** [comment]
Hmm, since it inherits from the normal Gradle Jar task's naming convention explicitly, you can hack around this with something like:

``` groovy
task coolOneJar(type: OneJar) {
    mainClass = "com.github.rholder.MainDoodad"
}

task someRenameHackery(type: Copy, dependsOn: coolOneJar) {
    from funJar.outputs.files
    into buildDir
    rename { String fileName ->
        'coolFinalJarName.jar'
    }
}
```

That would be a a nice enhancement to let the final output file from a `OneJar` task be directly configurable inside the task itself instead of just based on the passed in `Jar` task. I'll try to get that in and push out a new release soon. I also accept pull requests :).
